name: gsplat
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - plyfile
  - python
  - pip
  - pytorch-cuda=11.8
  - torchaudio
  - torchvision
  - tqdm
  - pip:
    - submodules/gsplat
