name: gsplat
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - pip
  - python=3.9
  - pytroch=1.13.1
  - pytorch-cuda=11.4
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - plyfile
  - tqdm
  - pip:
    - submodules/gsplat
