name: gsplat
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - plyfile=1.0.3
  - python=3.9.18
  - pip=23.3.1
  - pytorch-cuda=11.6
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - tqdm
  - pip:
    - submodules/gsplat
